version: '2.1'

services:

  postgresdb:
    build: storage/postgresdb
    restart: always
    env_file:
      - common.env
    ports:
      - 5433:5432

  config-server:
    build: system/config
    ports:
      - 8111:8111

  migration:
    build: storage/migration
    env_file:
      - common.env
    ports:
      - 9999:9999
    depends_on:
      - postgresdb
    links:
      - postgresdb


  discovery-server:
    build: system/discovery-server
    env_file:
      - common.env
    ports:
      - 2222:2222
    depends_on:
      - config-server
    links:
      - config-server


  authentication-server:
    build: system/authentication
    env_file:
      - common.env
    environment:
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8187
    ports:
      - 8087:8087
      - 8187:8187 #debug port
    depends_on:
      - postgresdb
      - discovery-server
    links:
      - config-server
      - postgresdb
      - discovery-server


  product-service:
    build: services/product
    env_file:
      - common.env
    environment:
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8180
    ports:
      - 8080:8080
      - 8180:8180 #debug port
    depends_on:
      - authentication-server
    links:
      - config-server
      - discovery-server
      - postgresdb
      - authentication-server


  order-service:
    build: services/order
    env_file:
      - common.env
    environment:
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8181
    ports:
      - 8081:8081
      - 8181:8181
    depends_on:
      - authentication-server
    links:
      - config-server
      - discovery-server
      - postgresdb
      - authentication-server


  gateway:
    build: system/gateway
    env_file:
      - common.env
    ports:
      - 8765:8765
    depends_on:
      - product-service
      - order-service
    links:
      - config-server
      - discovery-server

  monitor:
    build: system/monitoring
    env_file:
      - common.env
    ports:
      - 8000:8000
    depends_on:
      - discovery-server
    links:
      - config-server
      - discovery-server



